version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_DB:-app}:${POSTGRES_PASSWORD:-!sympass101;!}@127.0.0.1:5432/${POSTGRES_DB:-app}
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  db:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!sympass101;!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
