version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_DB:-app}:${POSTGRES_PASSWORD:-!sympass101;!}@127.0.0.1:5432/${POSTGRES_DB:-app}
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

###> doctrine/doctrine-bundle ###
  db:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!sympass101;!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
